#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE user_db;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE user_db TO "$POSTGRES_USER";
EOSQL